all: cyoa-step1 cyoa-step2 #cyoa-step3 cyoa-step4

cyoa-step1: cyoa-step1.cpp page.hpp story.hpp
	g++ -o cyoa-step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp page.hpp story.hpp
cyoa-step2: cyoa-step2.cpp
	g++ -o cyoa-step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp
cyoa-step3: cyoa-step3.cpp
	g++ -o cyoa-step3 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step3.cpp
cyoa-step4: cyoa-step4.cpp
	g++ -o cyoa-step4 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step4.cpp

.PHONY: clean
clean:
	rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
